# SPDX-FileCopyrightText: 2026 Jinghao Hu
# SPDX-License-Identifier: MIT

"""Public package interface for pyKDEX.

Author:
    Jinghao Hu
"""

from __future__ import annotations

__author__ = "Jinghao Hu"
__license__ = "MIT"
__version__ = "0.0.14"

from pykdex.adapters import from_networkx_graph, from_osmnx_graph, network_from_place
from pykdex.bandwidths import (
    AbramsonBandwidth,
    BalloonKNNBandwidth,
    BandwidthMatrix,
    BaseBalloonBandwidth,
    BaseHeatTime,
    BaseNetworkBandwidth,
    FixedBandwidth,
    FixedHeatTime,
    FixedNetworkBandwidth,
    HeatLeastSquaresCVTime,
    HeatLikelihoodCVTime,
    KNNBandwidth,
    LeastSquaresCVBandwidth,
    LikelihoodCVBandwidth,
    NetworkKNNBandwidth,
    NetworkLeastSquaresCVBandwidth,
    NetworkLikelihoodCVBandwidth,
    NetworkTimeBandwidths,
    NetworkTimeKNNBandwidth,
)
from pykdex.core import (
    BandwidthSelectionResult,
    HeatNetworkBatchResult,
    NetworkField,
    NetworkTimeBandwidthSelectionResult,
    NetworkTimeField,
    SpatialKDEResult,
    SpatiotemporalBandwidthSelectionResult,
    SpatiotemporalKDEResult,
)
from pykdex.corrections import (
    BaseBoundaryCorrection,
    NoBoundaryCorrection,
    ReflectionCorrection,
    RenormalizationCorrection,
)
from pykdex.data import (
    DataProvenance,
    DataValidationReport,
    GridSupport,
    KDEDataset,
    PointSupport,
    SpatialBoundary,
    SpatialEvents,
    SpatiotemporalEvents,
    SpatiotemporalGridSupport,
    SpatiotemporalPointSupport,
    TemporalCoordinates,
)
from pykdex.datasets import (
    load_bimodal_points,
    load_bounded_square,
    load_cross_network,
    load_disconnected_network,
    load_osmnx_fixture,
    load_ring_network,
    load_t_junction,
    make_bimodal_events,
    make_grid_network,
    make_moving_hotspot_events,
)
from pykdex.estimators import (
    HeatNetworkExperiment,
    HeatNetworkKDE,
    NetworkKDE,
    SpatialKDE,
    SpatiotemporalKDE,
    TemporalNetworkKDE,
)
from pykdex.kernels import (
    EpanechnikovKernel,
    ExponentialKernel,
    GaussianKernel,
    QuarticKernel,
    TriangularKernel,
    UniformKernel,
    get_kernel,
)
from pykdex.metrics import EuclideanMetric
from pykdex.network import (
    ContinuousJunctionPolicy,
    DiscontinuousJunctionPolicy,
    HeatComputePlan,
    JunctionPolicy,
    LinearNetwork,
    LixelSupport,
    NetworkDataset,
    NetworkDistanceAsset,
    NetworkEvents,
    NetworkHeatOperator,
    NetworkLocations,
    NetworkWorkspace,
    PropagationRecord,
    PropagationTrace,
    SimpleJunctionPolicy,
    SnapResult,
    TraversalResult,
    TraversalState,
    build_event_event_distances,
    build_event_lixel_distances,
    build_heat_compute_plan,
    build_network_distance_asset,
    build_network_heat_operator,
    get_junction_policy,
    snap_events,
    trace_network_propagation,
    truncated_traversal,
)
from pykdex.network_time import (
    ArixelSupport,
    NetworkTimeDistanceAsset,
    NetworkTimeEvents,
    NetworkTimeWorkspace,
    build_network_time_distance_asset,
)
from pykdex.persistence import (
    WorkspaceManifest,
    load_network_time_workspace,
    load_network_workspace,
    save_network_time_workspace,
    save_network_workspace,
)
from pykdex.selection import (
    HeatLeastSquaresCV,
    HeatLikelihoodCV,
    HeatSelectionCache,
    LeastSquaresCV,
    LikelihoodCV,
    NetworkLeastSquaresCV,
    NetworkLikelihoodCV,
    NetworkSelectionCache,
    NetworkTimeBandwidthExperiment,
    NetworkTimeSelectionCache,
    SpatiotemporalBandwidthExperiment,
)
from pykdex.spatiotemporal import (
    SpatiotemporalDistanceAsset,
    build_spatiotemporal_distance_asset,
)
from pykdex.temporal import BaseTimeDomain, CyclicTimeDomain, LinearTimeDomain

__all__ = [
    "SpatialKDE",
    "SpatiotemporalKDE",
    "TemporalNetworkKDE",
    "NetworkKDE",
    "HeatNetworkKDE",
    "HeatNetworkExperiment",
    "HeatNetworkBatchResult",
    "SpatialKDEResult",
    "NetworkField",
    "NetworkTimeField",
    "NetworkTimeBandwidthSelectionResult",
    "BandwidthSelectionResult",
    "SpatiotemporalKDEResult",
    "SpatiotemporalBandwidthSelectionResult",
    "SpatialEvents",
    "TemporalCoordinates",
    "SpatiotemporalEvents",
    "SpatiotemporalPointSupport",
    "SpatiotemporalGridSupport",
    "BaseTimeDomain",
    "LinearTimeDomain",
    "CyclicTimeDomain",
    "SpatiotemporalDistanceAsset",
    "build_spatiotemporal_distance_asset",
    "PointSupport",
    "GridSupport",
    "SpatialBoundary",
    "KDEDataset",
    "DataProvenance",
    "DataValidationReport",
    "make_bimodal_events",
    "make_moving_hotspot_events",
    "load_bimodal_points",
    "load_bounded_square",
    "load_t_junction",
    "load_cross_network",
    "load_ring_network",
    "load_disconnected_network",
    "load_osmnx_fixture",
    "make_grid_network",
    "LinearNetwork",
    "NetworkEvents",
    "NetworkHeatOperator",
    "HeatComputePlan",
    "build_network_heat_operator",
    "build_heat_compute_plan",
    "SnapResult",
    "snap_events",
    "LixelSupport",
    "NetworkWorkspace",
    "NetworkDataset",
    "NetworkTimeEvents",
    "ArixelSupport",
    "NetworkTimeDistanceAsset",
    "build_network_time_distance_asset",
    "NetworkTimeWorkspace",
    "WorkspaceManifest",
    "save_network_workspace",
    "load_network_workspace",
    "save_network_time_workspace",
    "load_network_time_workspace",
    "NetworkLocations",
    "NetworkDistanceAsset",
    "build_network_distance_asset",
    "build_event_event_distances",
    "build_event_lixel_distances",
    "TraversalState",
    "TraversalResult",
    "truncated_traversal",
    "JunctionPolicy",
    "SimpleJunctionPolicy",
    "DiscontinuousJunctionPolicy",
    "ContinuousJunctionPolicy",
    "get_junction_policy",
    "PropagationRecord",
    "PropagationTrace",
    "trace_network_propagation",
    "from_networkx_graph",
    "from_osmnx_graph",
    "network_from_place",
    "FixedBandwidth",
    "BaseBalloonBandwidth",
    "BandwidthMatrix",
    "BalloonKNNBandwidth",
    "BaseNetworkBandwidth",
    "FixedNetworkBandwidth",
    "NetworkKNNBandwidth",
    "NetworkLikelihoodCVBandwidth",
    "NetworkLeastSquaresCVBandwidth",
    "NetworkTimeBandwidths",
    "NetworkTimeKNNBandwidth",
    "BaseHeatTime",
    "FixedHeatTime",
    "HeatLikelihoodCVTime",
    "HeatLeastSquaresCVTime",
    "KNNBandwidth",
    "AbramsonBandwidth",
    "LikelihoodCVBandwidth",
    "LeastSquaresCVBandwidth",
    "LikelihoodCV",
    "LeastSquaresCV",
    "NetworkLikelihoodCV",
    "NetworkLeastSquaresCV",
    "NetworkSelectionCache",
    "NetworkTimeBandwidthExperiment",
    "NetworkTimeSelectionCache",
    "HeatLikelihoodCV",
    "HeatLeastSquaresCV",
    "HeatSelectionCache",
    "SpatiotemporalBandwidthExperiment",
    "BaseBoundaryCorrection",
    "NoBoundaryCorrection",
    "RenormalizationCorrection",
    "ReflectionCorrection",
    "EuclideanMetric",
    "GaussianKernel",
    "EpanechnikovKernel",
    "QuarticKernel",
    "TriangularKernel",
    "UniformKernel",
    "ExponentialKernel",
    "get_kernel",
    "__version__",
]
