# SPDX-FileCopyrightText: 2026 Jinghao Hu
# SPDX-License-Identifier: MIT

"""Public package interface for pyKDEX.

Author:
    Jinghao Hu
"""

from __future__ import annotations

__author__ = "Jinghao Hu"
__license__ = "MIT"
__version__ = "0.0.9"

from pykdex.adapters import from_networkx_graph, from_osmnx_graph, network_from_place
from pykdex.bandwidths import (
    AbramsonBandwidth,
    BalloonKNNBandwidth,
    BandwidthMatrix,
    BaseBalloonBandwidth,
    BaseNetworkBandwidth,
    FixedBandwidth,
    FixedNetworkBandwidth,
    KNNBandwidth,
    LeastSquaresCVBandwidth,
    LikelihoodCVBandwidth,
    NetworkKNNBandwidth,
    NetworkLeastSquaresCVBandwidth,
    NetworkLikelihoodCVBandwidth,
)
from pykdex.core import BandwidthSelectionResult, NetworkField, SpatialKDEResult
from pykdex.corrections import (
    BaseBoundaryCorrection,
    NoBoundaryCorrection,
    ReflectionCorrection,
    RenormalizationCorrection,
)
from pykdex.data import (
    DataProvenance,
    DataValidationReport,
    GridSupport,
    KDEDataset,
    PointSupport,
    SpatialBoundary,
    SpatialEvents,
)
from pykdex.datasets import (
    load_bimodal_points,
    load_bounded_square,
    load_cross_network,
    load_disconnected_network,
    load_osmnx_fixture,
    load_ring_network,
    load_t_junction,
    make_bimodal_events,
    make_grid_network,
)
from pykdex.estimators import HeatNetworkKDE, NetworkKDE, SpatialKDE
from pykdex.kernels import (
    EpanechnikovKernel,
    ExponentialKernel,
    GaussianKernel,
    QuarticKernel,
    TriangularKernel,
    UniformKernel,
    get_kernel,
)
from pykdex.metrics import EuclideanMetric
from pykdex.network import (
    ContinuousJunctionPolicy,
    DiscontinuousJunctionPolicy,
    JunctionPolicy,
    LinearNetwork,
    LixelSupport,
    NetworkDataset,
    NetworkDistanceAsset,
    NetworkEvents,
    NetworkHeatOperator,
    NetworkLocations,
    NetworkWorkspace,
    PropagationRecord,
    PropagationTrace,
    SimpleJunctionPolicy,
    SnapResult,
    TraversalResult,
    TraversalState,
    build_event_event_distances,
    build_event_lixel_distances,
    build_network_distance_asset,
    build_network_heat_operator,
    get_junction_policy,
    snap_events,
    trace_network_propagation,
    truncated_traversal,
)
from pykdex.selection import (
    LeastSquaresCV,
    LikelihoodCV,
    NetworkLeastSquaresCV,
    NetworkLikelihoodCV,
    NetworkSelectionCache,
)

__all__ = [
    "SpatialKDE",
    "NetworkKDE",
    "HeatNetworkKDE",
    "SpatialKDEResult",
    "NetworkField",
    "BandwidthSelectionResult",
    "SpatialEvents",
    "PointSupport",
    "GridSupport",
    "SpatialBoundary",
    "KDEDataset",
    "DataProvenance",
    "DataValidationReport",
    "make_bimodal_events",
    "load_bimodal_points",
    "load_bounded_square",
    "load_t_junction",
    "load_cross_network",
    "load_ring_network",
    "load_disconnected_network",
    "load_osmnx_fixture",
    "make_grid_network",
    "LinearNetwork",
    "NetworkEvents",
    "NetworkHeatOperator",
    "build_network_heat_operator",
    "SnapResult",
    "snap_events",
    "LixelSupport",
    "NetworkWorkspace",
    "NetworkDataset",
    "NetworkLocations",
    "NetworkDistanceAsset",
    "build_network_distance_asset",
    "build_event_event_distances",
    "build_event_lixel_distances",
    "TraversalState",
    "TraversalResult",
    "truncated_traversal",
    "JunctionPolicy",
    "SimpleJunctionPolicy",
    "DiscontinuousJunctionPolicy",
    "ContinuousJunctionPolicy",
    "get_junction_policy",
    "PropagationRecord",
    "PropagationTrace",
    "trace_network_propagation",
    "from_networkx_graph",
    "from_osmnx_graph",
    "network_from_place",
    "FixedBandwidth",
    "BaseBalloonBandwidth",
    "BandwidthMatrix",
    "BalloonKNNBandwidth",
    "BaseNetworkBandwidth",
    "FixedNetworkBandwidth",
    "NetworkKNNBandwidth",
    "NetworkLikelihoodCVBandwidth",
    "NetworkLeastSquaresCVBandwidth",
    "KNNBandwidth",
    "AbramsonBandwidth",
    "LikelihoodCVBandwidth",
    "LeastSquaresCVBandwidth",
    "LikelihoodCV",
    "LeastSquaresCV",
    "NetworkLikelihoodCV",
    "NetworkLeastSquaresCV",
    "NetworkSelectionCache",
    "BaseBoundaryCorrection",
    "NoBoundaryCorrection",
    "RenormalizationCorrection",
    "ReflectionCorrection",
    "EuclideanMetric",
    "GaussianKernel",
    "EpanechnikovKernel",
    "QuarticKernel",
    "TriangularKernel",
    "UniformKernel",
    "ExponentialKernel",
    "get_kernel",
    "__version__",
]
